((nil . ((cmake-ide--build-dir-var . "./")
	 (projectile-project-name . "fucker_sql")
	 (projectile-project-root . "/Users/joyeongchan/projects/jyc-sql/")
	 (jyc-program-args . "./test_sql.txt")
	 (eval . (defun jyc-sql-compile()
		   (interactive)
		   (exec-shell-command-with-buffer
		    (format "python %s/build.py --bin %s --home %s --debug --cmd " projectile-project-root projectile-project-name projectile-project-root)
		    (format "%s-%s" "*compilation*" projectile-project-name))
		   (compilation-minor-mode t)
		   (switch-to-buffer-other-window (other-buffer (current-buffer) 1))
		   ))
	 (eval . (defun jyc-sql-compile-exec()
		   (interactive)
		   (exec-shell-command-with-buffer
		    (format "python %s/build.py --bin %s --home %s --debug --cmd --exec --args %s " projectile-project-root projectile-project-name projectile-project-root jyc-program-args)
		    (format "%s-%s" "*compilation*" projectile-project-name))
		   ;; (compilation-minor-mode t)
		   (switch-to-buffer-other-window (other-buffer (current-buffer) 1))
		   ))
	 (eval . (local-set-key (kbd "<f5>") 'jyc-sql-compile))
	 (eval . (local-set-key (kbd "<f6>") 'jyc-sql-compile-exec))
	 )))
